# SUMMARY.md uses h1 to indicate the section title
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/md025.md
single-h1: false
line-length:
    line_length: 100

# SUMMARY.md uses empty links to show table of contents items that are not yet implemented
no-empty-links: false

no-inline-html:
    allowed_elements:
        - img # we display the logo using an img tag, so it can be floated beside the text
