[package]
name = "how-to-overwrite-regions"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.3"
derive_setters = "0.1.6"
crossterm = "0.27.0"
lipsum = "0.9.1"
ratatui = "0.26.1"
